AWSTemplateFormatVersion: '2010-09-09'
Description: Root template for production infrastructure

Parameters:
  EnvironmentName:
    Type: String
    Default: "production"
    Description: "The environment name (e.g., production)."

Resources:
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/my-devops-project-20240812-unique/templates/Compute.yaml
      Parameters:
        VPCId: !ImportValue production-VPCId
        PublicSubnetId: !ImportValue production-PublicSubnetId
        EnvironmentName: !Ref EnvironmentName